#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

produit_supprimer:
    path: '/produit/supprimer/{id}'
    controller: 'App\Controller\ProduitController::supprimerProduit'
    methods: ['DELETE']
